# Welcome to Jekyll!
title: PSUG Blog
email: #psug@domain.tld
description: Blog grouping the talks shown at the Scala User Group in Paris, France.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://psug.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: parisscalaug
github_username:  psug

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
